name: CICD Pipeline

on:
  push:
    branches: ["main"] 
jobs:
    compile:
        runs-on: ubuntu-latest 
steps:
  - uses: actions/checkout@v4
  - name: Set up JDK 21
    uses: actions/setup-java@v4
    with:
    java-version: '21'
    distribution: 'terminal'
    cache: maven
  - name: Build with Maven
    run: mvn -B package --file pom.xml
